---
title: "Importance of being uncertain\n\nHow samples are used to estimate population statistics and what this means in terms of uncertainty"
author: IBiG
date: "January 14th, 2020\n\n Points of Significance - Nature Methods"
output:
      xaringan::moon_reader:
        css: ["my.css","default", "default-fonts", "hygge"]
        chakra: libs/remark-latest.min.js
---

# Introduzione del ciclo di incontri

## Obiettivi
1. Pianificazione degli esperimenti
1. Raccolta dei dati
1. Analisi dei dati
1. Interpretazione dei risultati

--

## Modalita'
1. Gli incontri si svolgeranno come dei Journal clubs.
1. I membri dell'IBiG si prendereanno la responsabilita' di preparare gli incontri con **cadenza mensile**.    
1. Verra' utilizzato come linea guida la rubrica di _Nature Methods_: .bold[Point of Significance].
1. Ogni suggerimento o proposta di tema dai colleghi e' il benvenuto.

???

Le mie note

---
class: inverse

.center[
# Importance of being uncertain
]

#### How samples are used to estimate population statistics and what this means in terms of uncertainty 

<br>
<br>

--

.content-box-grey[
.center[.black[Statistics does not tell us whether we are right. 

It tells us the chances of being wrong.
]]]

???

La statistica non da un numero che ci dice se abbiamo ragione ho meno, la statistica da un range di probabilita'. Da incertezza

---
.center[
## 1936 USA Presidential Election

### Central event in the history of statistics and polling
]

--
.pull-left[
.small[
### Literary Digest

- Predict correctly the previous 4 elections

- 10M people sample

- Republican Alfred Mossman Landon wins by large majority
]
]

--

.pull-right[
.small[
### Statistician George Gallup

- 0.05M people sample

- Democratic Franklin D. Roosevelt wins 

- With 0.003M he replicated the results of Literary Digest
]
]

--

1. Roosevelt won
 
1. Literary Digest ceased publishing within a few months of the election

